# let check probe of nginx in port 3000
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-web
  namespace: nginx-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web

  template:
    metadata:
      labels:
        app: nginx-web
    
    spec:
      containers:
      - name: nginx-web
        image:  nginx:latest
        ports:
        - containerPort:  3000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
